spring:
  data:
    redis:
      host: localhost
      port: 6379
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: my_keyspace
    local-datacenter: datacenter1
    schema-action: create_if_not_exists